env: "local"
db: 
  path: "../../data/chords_app.db"
server:
  host: "0.0.0.0"
  port: 8080
roles:
  user: user
  admin: admin
jwt:
  access_token_exp_time_min: 15
  access_token_secret_key: "secret1"
  refresh_token_exp_time_days: 30
  refresh_token_secret_key: "secret2"
  